### ISSUE TITLE
`CLIPTokenizer` does not add tokens for `<|startoftext|>` and `<|endoftext|>` to outputs when using only using `merge_path` input variable

### ISSUE THREAD

**Issue by ProGamerGov** [pytorch/text#1630]
## 🐛 Bug

I'm not 100% sure if this is a bug, but the CLIP tokenizer does not add tokens for `<|startoftext|>` and `<|endoftext|>` to outputs when using the `merge_path` input variable. In [open_clip](https://github.com/mlfoundations/open_clip/blob/main/src/clip/tokenizer.py) and [OpenAI](https://github.com/openai/CLIP/blob/main/clip/simple_tokenizer.py)'s CLIP tokenizers, the `<|startoftext|>` token is always added in front of any inputs and the `<|endoftext|>` token is added at the end of inputs.

 In the code, `<|startoftext|>` & `<|endoftext|>` are added to the vocab, but never used: https://github.com/pytorch/text/blob/main/torchtext/transforms.py#L371

**Comment by ProGamerGov** [comment]
Outputs also appear to be a list of strings of numbers, rather than a tensor or even a list of numbers: 

```
test_str = "This is a test"
test_output = clip_tokenizer(test_str)
print(test_output) # ['589', '533', '320', '1628']
```

**Comment by Nayef211** [comment]
cc @abhinavarora since you have the most context on the CLIP tokenizer

**Comment by abhinavarora** [comment]
@ProGamerGov Thank you again for reporting this. This was explicitly not added to the tokenizer to keep it as generic as possible. The expectation is that anyone writing a `CLIPTransform` would add them manually after calling the tokenizer so that all users have the flexibility to choose whether they want to add special tokens or not. The reason they have been added to the vocab to keep the vocab consistent when users only provide the merges file and not the `encoder.json`.

**Comment by ProGamerGov** [comment]
@abhinavarora Yeah, that makes sense!
