### ISSUE TITLE
torchtext.data.Field is not working but torchtext.legacy.data.Field is! The documentation doesn't help either

### ISSUE THREAD

**Issue by aashish-chaubey** [pytorch/text#1636]
## ❓ Questions and Help
Made a fresh installation of torchtext and followed the documentation to use the Field 
```python
from torchtext import data
```
For some reason, this doesn't work and throws the following error
```
AttributeError: module 'torchtext.data' has no attribute 'Field'
```
However, this works
```python
from torchtext.legacy import data
```

The specification of my systems are mentioned below.

```
torchtext version:  0.11.2
torch version:  1.10.2+cu102
OS:  Linux 5.14.0-1024-oem #26-Ubuntu 
Python verson:  3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
```

**Description**
By using the legacy, I am able to create the field. Also, I read that this is usually the case when there is a version mismatch. Any help?

**Comment by Nayef211** [comment]
Hi @aashish-chaubey. I believe the `Field` class has been moved to the legacy folder since torchtext `0.9.0` release. Here are the release notes that go into more detail about this https://github.com/pytorch/text/tree/v0.11.2/torchtext/legacy#legacy.  The legacy folder is deleted altogether in https://github.com/pytorch/text/pull/1437 and will not be available in torchtext `0.12.0` onwards.
