### ISSUE TITLE
Vocab class stoi will map `<pad>` and anything unknown to 0?

### ISSUE THREAD

**Issue by cyxtj** [pytorch/text#165]
I'm new to torchtext and trying to learn the way to construct a vocabulary used for NMT.  
I find it is a little strange for the Vocab class which will map both `<pad>` and anything unknown to the same index 0. Is that correct? What is the purpose of that? If I provide args `special=[]`, will that cause some problem?

In practice, usually, we have an embedding matrix, should the index=0 row representing UNKNOWN?

**Comment by jekbradbury** [comment]
if you provide a `pad_token` (but no `init_token` or `eos_token`) it will map unknown words and `<unk>` to 0 and the pad token (i.e., `<pad>` if you use the default) to 1. So the index=0 row should represent unknown, which is the behavior used by the built-in GloVe loaders.

**Comment by Halfish** [comment]
@jekbradbury I still can not get the result you described.

I run the following,
```python
v = torchtext.vocab.Vocab(Counter(['alice', 'bob', 'alice']))
print(v.itos)
print(v.stoi['john'])
```
and I got the output like
```
['<pad>', 'alice', 'bob']
0
```

That is not what I want, because I can not see an '<unk>' here. I expect `v.itos` to be like `['<unk>', '<pad>', 'alice', 'bob']`, but it seems the default behavior of torchtext.vocab.Vocab does not add the `<unk>` symbol.

So I do it like this to get what I want,
```
v = torchtext.vocab.Vocab(Counter(['alice', 'bob', 'alice']), specials=['<unk>', '<pad>'])
```
