### ISSUE TITLE
Moving from Google Drive downloads to GitHub Releases

### ISSUE THREAD

**Issue by xhluca** [pytorch/text#1892]
## Issue

At the moment, there are 12 datasets that use Google Drive: https://github.com/pytorch/text/search?l=Python&q=drive.google.com

GDrive has been the source of various issues, for example in https://github.com/pytorch/text/issues/1676 and quota exceeded in https://github.com/pytorch/text/issues/1359

As an alternative, GitHub Releases allow up to 2GB files, can be downloaded directly from HTTP (thus the dependency on a custom function for downloading from GDrive can be removed). Google Drive links are also more easily removed (accidentally), whereas for GitHub releases, you would need someone with a release manager permission or higher to explicitly remove it; you can also have multiple dataset releases to avoid this issue, e.g. a special release tag like `data-<name>` instead of `v.X.Y.Z`.

**Comment by Nayef211** [comment]
@xhluca thanks for calling out this issue. Unfortunately, torchtext explicitly does take responsibility for hosting any datasets due to legal issues. I'd recommend reaching out directly to the organization that hosts the datasets and requesting if they can migrate to GitHub Releases (a task that might be more involved). Another thing to note is that a lot of text datasets exceed the 2GB file limit so that may be a limitation for many organizations when they decide what platform to store their datasets on.

**Comment by xhluca** [comment]
Thanks for your response. I'll close this issue.

As an aside, I'm happy to learn more about the legal aspect of hosting data, as this is an important subject and (as researcher) I'm directly affected, either to consume or to publish datasets. I'm mainly curious about this:
* Is it due to internal compliance policy (within the pytorch team)?
* Or do the datasets explicitly prohibit re-hosting the datasets due to licensing? 
* For example, with datasets with a CC-BY-SA license, the license would allow re-hosting as long as the data stays the same and the authors are cited. So would the concern be liabilities?
