### ISSUE TITLE
Datasets used in tests

### ISSUE THREAD

**Issue by salman1993** [pytorch/text#19]
Hello,

Can you please provide the datasets that are used in the "tests"?
It references to this path: "~/chainer-research/jmt-data/pos_wsj/pos_wsj" but I can't find the pos_wsj dataset.
Since the docs are not that great, I think the tests will be a good place to start learning.

Also, in the "tests/vocab.py" it references the Glove 300d vectors but it is not whether it is a text file or what?

**Comment by jekbradbury** [comment]
Yeah, currently the `tests` directory contains examples of use with custom datasets rather than actual unit tests. That dataset is a TSV with tokenized text and space-separated POS labels; the licensing and distribution of the old text tagging datasets is kind of complicated but there are probably similarly formatted dataset available online.
And GloVe vectors should be automatically downloaded and extracted if you ask for them to be used by passing a `wv_type` to the `build_vocab` method.

**Comment by salman1993** [comment]
got it. thanks. 
i think the tests for vocab.py are outdated - there is nothing called 'wv_path'. you might want to check that out but I'll close this issue.
TypeError: __init__() got an unexpected keyword argument 'wv_path'
