### ISSUE TITLE
cannot import name 'BERTTokenizer' from 'torchtext.transforms'

### ISSUE THREAD

**Issue by kaoutaar** [pytorch/text#1902]
## 🐛 Bug

Hi, 
I am working on kaggle, i see they use torchtext  `0.12.0`
When i try to :
`from torchtext.transforms import BERTTokenizer`

I get : 

```
----> 1 from torchtext.transforms import BERTTokenizer

ImportError: cannot import name 'BERTTokenizer' from 'torchtext.transforms' (/opt/conda/lib/python3.7/site packages/torchtext/transforms.py)
```

**Comment by Nayef211** [comment]
Hey @kaoutaar. The `BERTTokenizer` was only added to torchtext in the 0.13 release. You can see the [commit for it here](https://github.com/pytorch/text/commit/da509e14b2f972794d0513355c2589be0bd1ab23). As such you would need to update the torchtext version to 0.13 on Kaggle in order to be able to use it.

**Comment by kaoutaar** [comment]
Ah ok! Thanks
