### ISSUE TITLE
build_vocab as one hot encoded vector

### ISSUE THREAD

**Issue by ram-g-athreya** [pytorch/text#313]
Hi

Is there any way to **build_vocab** as one hot encoded vectors instead of pre-trained models? If not what are possible alternatives that we can use for the same.

Thanks
Ram G Athreya

**Comment by nh007cs** [comment]
This is an interesting problem!

**Comment by mttk** [comment]
You can likely do this with the current version of the vocab. When iterating over the data, imagine your batch is of shape BxT (batch_size x sequence length). Each element in the batch is a sequence of indices from the vocabulary.

You can convert each element in the T dimension to a one-hot embedding:
```
one_hot_batch = torch.nn.functional.one_hot(batch, len(vocab))
```
But since this matrix will be very large if your vocab is large, you might want to convert it to a multi-hot vector, where you would create a new tensor of size `batch_size, len(vocab)` and fill ones for the words present in each instance of the batch?

**Comment by ZeerakW** [comment]
@mttk Amazing! I'll try it out tomorrow to confirm that it works (my vocabulary is small) and I'll try with a multi hot encoding sometime in the next week and report back (potentially with code).

**Comment by ZeerakW** [comment]
Oh forgot to report back. Using ```torch.functional.one_hot``` works on a batch level. I haven't had time to try out a multi-hot  vector so can't say if that'll work. But perhaps this can be closed now?

**Comment by mttk** [comment]
Yup, thanks for confirming!
