### ISSUE TITLE
AttributeError: type object 'Example' has no attribute 'fromTSV'

### ISSUE THREAD

**Issue by ben0it8** [pytorch/text#387]
I have lately encountered  **AttributeError: type object 'Example' has no attribute 'fromTSV'** which have never happened before. It was raised when calling TabularDataset.splits().
I'm using torchtext 0.2.1.

Thank you for any help!

**Comment by mttk** [comment]
`fromTSV` was removed in favor of `fromCSV`, which handles both cases since #217. However, this happened after 0.2.1 (https://github.com/pytorch/text/blob/v0.2.1/torchtext/data/example.py), so I'm not sure what's the cause of the error.

Could you remove and reinstall the package and see if this happens again?

**Comment by zhangguanheng66** [comment]
@ben0it8 if it still happens after 0.4.0, please re-open the issue.
