### ISSUE TITLE
does pytorch team stop developing torchtext?

### ISSUE THREAD

**Issue by speedcell4** [pytorch/text#494]
I notice the latest commit is in Nov 2018. 
does that mean pytorch team have already stopped developing torchtext?
if yes, then official suggestion is migrating to pytext instead?

**Comment by mttk** [comment]
I've been maintaining torchtext up until Nov, when I had some major issues with my hand causing me to miss out on coding for a bit over a month. Since I'm doing maintenance in my free time, I've been a bit overwhelmed with the backlog accumulated on my job in that month and haven't _yet_ been able to clean up the repository.

I'll get to it in the near future, but the maintenance has not been stopped, merely put on hold. I'm not sure about the interplay of pytext & torchtext, but the plan AFAIK wasn't to replace one with the other.

**Comment by speedcell4** [comment]
I see, thank you so much~
