### ISSUE TITLE
Implementing C++ Side

### ISSUE THREAD

**Issue by ShahriarSS** [pytorch/text#559]
Hi @soumith I want to work on torchtext and implement its C++ API. I'm less familiar with torchtext so where can I can start?

**Comment by zhangguanheng66** [comment]
@ShahriarSS Thanks for the proposal. We do want to implement its C++ API (similarly to [TorchVision](https://github.com/pytorch/vision/tree/master/torchvision/csrc)). If you have some specific APIs in mind, please briefly describe here and move forward. Otherwise, we can start with some simple APIs and build the bindings first. Again, appreciate for your contribution.

**Comment by ShahriarSS** [comment]
@zhangguanheng66 As I said I'm less familiar with ```torchtext``` but we will have a problem implementing C++ side because we don't have ```spacy``` for tokenization and lemmatization and there aren't any other good libraries that I know of to do these tasks in c++ (I have checked out a few). What do you suggest we do here?

**Comment by zhangguanheng66** [comment]
@ShahriarSS IMO, it would be great if you could start with some simple functions in C++ and build the bindings. An example is the text normalization function here (https://github.com/pytorch/text/blob/844242a3a50759ed82c81a3814476640a31c52ae/torchtext/datasets/text_classification.py#L36-L45. Build the bindings and compile/test it. It will facilitate our future implementation on the C++ side.

Another API, which is more substantial, is the dictionary. Currently, torchtext uses collections.Counter for vocab. We would like to implement the dictionary similar to fastText here (https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc). You contribution to this will definitely help a lot.
