### ISSUE TITLE
BucketIterator vs BPTTIterator Tensor vs Not

### ISSUE THREAD

**Issue by Deepblue129** [pytorch/text#60]
BPTTIterator numericalizes the data and turns it into a tensor while BucketIterator does not. 

Do you think the behavior here should be consistent? Either the data is always converted to tensors or is not?

**Comment by nelson-liu** [comment]
Hmm, I'm pretty sure `BucketIterator` numericalizes and outputs Tensors as well. Do you have a example to reproduce this?

It's a bit confusing, since `BPTTIterator` calls `Field.numericalize` [here](https://github.com/pytorch/text/blob/master/torchtext/data/iterator.py#L145) while `BucketIterator` calls `Field.numericalize` when it constructs and returns a `Batch` object [here](https://github.com/pytorch/text/blob/master/torchtext/data/batch.py#L21)

**Comment by jekbradbury** [comment]
Yes, they both numericalize/tensorify their data.  I used tensor-based batching for the BPTTIterator (i.e., take the whole dataset, turn it into a single tensor, then walk through the tensor) because that's both simpler and significantly faster for the special case of language modeling (where every batch is the same length and you're basically just striding forwards over your dataset). In particular, BPTTIterator was ported from the PyTorch language modeling example, which was itself ported from some Torch code that does this.

**Comment by Deepblue129** [comment]
@nelson-liu  @jekbradbury Thanks guys! 

Your right I missed `numericalize` in the `Batch` object.
