### ISSUE TITLE
Different design on Text Classification Dataset

### ISSUE THREAD

**Issue by akurniawan** [pytorch/text#608]
## ❓ Questions and Help

**Description**

Hi, I notice there is a noticeably different approach for text classification dataset. In test folder, for text classification, we are no longer using data.Fields nor data.Iterator anymore and instead build our own iterator for that dataset. Is there any change of direction in terms of the design from this moment forward? Or it's just for this particular dataset?

**Comment by zhangguanheng66** [comment]
@akurniawan We are currently redesigning torchtext dataset, especially `Field` class. There are a lot of things we propose to change and I will open an issue for open discussions later. 

In general, we would like to break `Field` class into several orthogonal modules/functionals because wrapping up tokenizers/vocab/Batch in a single class is difficult for users. We want to create some simple independent building blocks so users can build the pipeline as needed. We also want to make torchtext library more compatible with `torch.data.utils` (a.k.a. `Sampler`, `DataLoader`). 

Once we agree with the design internally, we will publish it for open discussions. The text classification dataset is an example for that. Feel free to reach out to us if you have any feedback.
@mttk @cpuhrsch

**Comment by akurniawan** [comment]
@zhangguanheng66 interesting! looking forward to that discussion!
One more question related to the new design, are you guys planning to add support to load data directly from cloud storage (gcs, s3, etc)? Since we already have [IterableDataset](https://pytorch.org/docs/stable/data.html#torch.utils.data.IterableDataset), would be nice to actually have built-in support to load text data from those as what the other framework has done for the past couple of years.
Just to be clear, what I mean by built-in is the capability to differentiate the storage type (local, cloud, etc) and optimize the way the data is loaded by the engine without user having to do any manual configuration.

**Comment by zhangguanheng66** [comment]
We don't have it on our current plan. But thanks for pointing it out and I will add it to our to-do lists.

> @zhangguanheng66 interesting! looking forward to that discussion!
> One more question related to the new design, are you guys planning to add support to load data directly from cloud storage (gcs, s3, etc)? Since we already have [IterableDataset](https://pytorch.org/docs/stable/data.html#torch.utils.data.IterableDataset), would be nice to actually have built-in support to load text data from those as what the other framework has done for the past couple of years.
> Just to be clear, what I mean by built-in is the capability to differentiate the storage type (local, cloud, etc) and optimize the way the data is loaded by the engine without user having to do any manual configuration.

**Comment by akurniawan** [comment]
thanks!
