### ISSUE TITLE
Feature Request: Implement sorting within batches

### ISSUE THREAD

**Issue by nelson-liu** [pytorch/text#62]
I don't think this is currently implemented -- pardon me if it is. It'd be great to sort within batches, most notably for use with `pack_padded_sequence`.

**Comment by jekbradbury** [comment]
Examples are currently sorted within batches if you use `Iterator(sort=True)` or `BucketIterator`, assuming that the `sort_key` you provide for deciding what should be batched together is the same one you want to use for `pack_padded_sequence`. This should be true for single-sequence tasks (e.g. classification) and you can do it for MT by sorting on the source sequence length rather than the interlaced key.

**Comment by nelson-liu** [comment]
got it, thanks!
