### ISSUE TITLE
Possible bug in LanguageModelingDataset

### ISSUE THREAD

**Issue by dasguptar** [pytorch/text#64]
In the code for [`LanguageModelingDataset`](https://github.com/pytorch/text/blob/master/torchtext/datasets/language_modeling.py), the original text seems to be pre-processed twice, viz.:

- `text += text_field.preprocess(line)` [at line 22](https://github.com/pytorch/text/blob/master/torchtext/datasets/language_modeling.py#L22)
- `examples = [data.Example.fromlist([text], fields)]` [at line 26](https://github.com/pytorch/text/blob/master/torchtext/datasets/language_modeling.py#L26), which in turn calls 
`setattr(ex, name, field.preprocess(val))` [at line 44 of example.py](https://github.com/pytorch/text/blob/master/torchtext/data/example.py#L44)

In fact, if I try to create a simple LanguageModelingDataset, I am getting an error as follows:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/riddasgu/.local/lib/python2.7/site-packages/torchtext/datasets/language_modeling.py", line 28, in __init__
    examples = [data.Example.fromlist([text], fields)]
  File "/home/riddasgu/.local/lib/python2.7/site-packages/torchtext/data/example.py", line 44, in fromlist
    setattr(ex, name, field.preprocess(val))
  File "/home/riddasgu/.local/lib/python2.7/site-packages/torchtext/data/field.py", line 91, in preprocess
    x = self.tokenize(x)
  File "/home/riddasgu/.local/lib/python2.7/site-packages/torchtext/data/field.py", line 63, in <lambda>
    tokenize=(lambda s: s.split()), include_lengths=False,
AttributeError: 'list' object has no attribute 'split'
```

**Comment by jekbradbury** [comment]
Looks like that was my mistake in a recent patch. What I think is supposed to happen here is that the first `preprocess` does the tokenization (it has to be this way because we need to split the corpus into segments with equal numbers of tokens) and the second one should be a no-op because [this line](https://github.com/pytorch/text/blob/master/torchtext/data/field.py#L90) used to include a check that the field data was a string. I'll add that back in.
